######################################################################
# Automatically generated by qmake (2.01a) Thu 19. Mar 23:01:56 2015
######################################################################

QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += console
#DEFINES += USE_THREADED_UPDATE

# Input
HEADERS += animal.hpp \
           matrix.hpp \
           neural-net.hpp \
           size-mismatch-exception.hpp \
           world.hpp \
           fish.hpp \
           interface.hpp \
           object.hpp \
           shaders.hpp \
           worker.hpp \
           utility.hpp \
           constants.hpp

SOURCES += main.cpp \
           animal.cpp \
           matrix.cpp \
           neural-net.cpp \
           size-mismatch-exception.cpp \
           world.cpp \
           fish.cpp \
           interface.cpp \
           object.cpp \
           model-shaders.cpp \
           primative-shaders.cpp \
           worker.cpp \
           utility.cpp
